### ISSUE TITLE
Build failure, undefined: Logger

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [advantageous/systemd-cloud-watch#20]
This appears to have bit-rotted.

I tried to build it using go version go1.11.6 linux/amd64, on Linux krestivo 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux

and got

```
go build
# github.com/advantageous/systemd-cloud-watch/cloud-watch
/home/krestivo/go/src/github.com/advantageous/systemd-cloud-watch/cloud-watch/journal_linux.go:11:11: undefined: Logger
```

**Comment by RaitoBezarius** [comment]
Same here using Arch Linux, linux 5.3, x86_64, precisely:
```
github.com/advantageous/systemd-cloud-watch/cloud-watch
# github.com/advantageous/systemd-cloud-watch/cloud-watch
../src/github.com/advantageous/systemd-cloud-watch/cloud-watch/journal_linux.go:17:12: error: reference to undefined name ‘NewSimpleLogger’
   17 |  logger := NewSimpleLogger("journal", config)
      |            ^
../src/github.com/advantageous/systemd-cloud-watch/cloud-watch/journal_linux.go:11:11: error: use of undefined type ‘Logger’
   11 |  logger  *Logger
      |           ^
../src/github.com/advantageous/systemd-cloud-watch/cloud-watch/journal_linux.go:64:17: error: reference to field ‘Info’ in object which has no fields or methods
   64 |   journal.logger.Info.Printf("NEXT location %d %v", loc, err)
      |                 ^
```

**Comment by seahow** [comment]
seeing this (or something similar) on Amazon Linux 2 

Dec 26 06:50:50 kv-streamer-1 systemd[1]: Started systemd-cloud-watch_linux.
Dec 26 06:50:50 kv-streamer-1 systemd[1]: Starting systemd-cloud-watch_linux...
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: main INFO: 2019/12/26 06:50:50 config.go:125: Loading config /etc/journald-cloudwatch.conf
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: main INFO: 2019/12/26 06:50:50 creators.go:31: Creating repeater that is conneting to AWS cloud watch
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: main INFO: 2019/12/26 06:50:50 workers.go:203: Success: Seek to head of systemd journal
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46a68d]
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: goroutine 12 [running]:
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: panic(0x7145e0, 0xc420010080)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/systemd-cloud-watch/cloud-watch.(*CloudWatchJournalRepeater).WriteBatch.func2(0x73c2c0, 0xc420149320)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/systemd-cloud-watch/cloud-watch/cloudwatch_journal_repeater.go:100 +0x15d
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/systemd-cloud-watch/cloud-watch.(*CloudWatchJournalRepeater).WriteBatch(0xc4200533b0, 0xc420194400, 0x64
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/systemd-cloud-watch/cloud-watch/cloudwatch_journal_repeater.go:175 +0x10c4
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/systemd-cloud-watch/cloud-watch.(*Runner).sendBatch(0xc42008f4a0)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/systemd-cloud-watch/cloud-watch/workers.go:45 +0xe8
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/systemd-cloud-watch/cloud-watch.(*Runner).addToCloudWatchBatch(0xc42008f4a0, 0xc4202249a0)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/systemd-cloud-watch/cloud-watch/workers.go:36 +0x7a
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/systemd-cloud-watch/cloud-watch.NewRunnerInternal.func1(0x6ed080, 0xc4202249a0)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/systemd-cloud-watch/cloud-watch/workers.go:74 +0x45
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/go-qbit/qbit.(*BaseReceiveQueueListener).Receive(0xc420012fc0, 0x6ed080, 0xc4202249a0)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/go-qbit/qbit/listener.go:74 +0x3e
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: github.com/advantageous/go-qbit/qbit.manageQueue(0x2710, 0xaec340, 0xc4201490e0, 0xaed820, 0xc420111ec0, 0xaed7c0, 0xc420012fc0)
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/go-qbit/qbit/queue-manager.go:111 +0xdb
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: created by github.com/advantageous/go-qbit/qbit.(*BasicQueueManager).startListener
Dec 26 06:50:50 kv-streamer-1 systemd-cloud-watch_linux[3420]: /gopath/src/github.com/advantageous/go-qbit/qbit/queue-manager.go:45 +0xfb
Dec 26 06:50:50 kv-streamer-1 systemd[1]: journald-cloudwatch.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 26 06:50:50 kv-streamer-1 systemd[1]: Unit journald-cloudwatch.service entered failed state.
Dec 26 06:50:50 kv-streamer-1 systemd[1]: journald-cloudwatch.service failed.

**Comment by krestivo-kdinfotech** [comment]
I ran into this and forked the project to fix it.

https://github.com/krestivo-kdinfotech/systemd-cloud-watch
